### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by portlek** [okyanus-mc/installer#1]
```
:: Getting Minecraft data
:: Downloading the latest Minecraft server for 1.14.3
:: Getting Fabric data
:: Downloading the latest Fabric Loader
:: Getting loader library data
:: Downloading the loader libraries
  => net.fabricmc:tiny-mappings-parser:0.1.1.8
Exception in thread "main" java.io.FileNotFoundException: .okyanus\libs\net.fabricmc:tiny-mappings-parser:0.1.1.8.jar (Dosya adı, dizin adı veya birim etiketi sözdizimi hatalı)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at club.issizler.okyanus.installer.Installer.download(Installer.kt:181)
        at club.issizler.okyanus.installer.Installer.main(Installer.kt:58)
        at club.issizler.okyanus.installer.Installer.main(Installer.kt)
```

**Comment by Admicos** [comment]
Just pushed a possible fix, can you try it now?
